# Page settings

baseURL = "http://example.org/"
languageCode = "en"
title = "Bootstrap 4 Blog Template For Developers"
theme = "hugo-devblog-theme"
googleAnalytics = "UA-XXXXXXX-Y"




[params]
    author = "Xiaoying Riley at 3rd Wave Media"
    description = "Blog Template"




    [params.profile]
        enable = true
        name = "Simon Doe"
        tagline = "Senior Software Engineer"
        avatar = "avatar.png"
